### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by iampapagray** [LinusU/php-bitcoin-address-validator#3]
Fatal error: Uncaught Error: Call to undefined function LinusU\Bitcoin\bcmul() in /var/www/html/oom/AddressValidator.php:82

**Comment by LinusU** [comment]
`bcmul()` is a function in php. This error means that the php version on your server has not been compiled with the necessary library, called BC Math (http://php.net/manual/en/book.bc.php). You need to talk to your server admin about this.

ref: https://www.drupal.org/project/yr_verdata/issues/1159010
